# Generated by Django 6.0.5 on 2026-06-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beranda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("regency_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="Regencies",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("province_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "regencies",
            },
        ),
        migrations.CreateModel(
            name="Villages",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("district_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "villages",
            },
        ),
    ]
