# Generated by Django 6.0.5 on 2026-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beranda", "0002_districts_regencies_villages"),
    ]

    operations = [
        migrations.AddField(
            model_name="districts",
            name="alt_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="districts",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="districts",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="regencies",
            name="alt_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="regencies",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="regencies",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="villages",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="villages",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
